//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanBook
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string StudentId { get; set; }
        public Nullable<bool> LoanReturn { get; set; }
        public string StudentName { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual LibUser LibUser { get; set; }
    }
}
